name: deploy
description: none
inputs:
  GCP_PROJECT_ID:
    required: true
    description: "Valid gcp project id"
  GCP_SA_KEY:
    required: true
    description: "Valid gcp credentials"
  GCP_DOCKER_REGISTRY:
    required: true
    description: "Valid docker registry ( artifact registry )"
  DOCKER_IMAGE_TAG:
    required: true
    description: "Docker image tag"
  GCP_K8S_CLUSTER_ID:
    required: true
    description: "Kubernetes cluster id"
  GCP_K8S_CLUSTER_ZONE:
    required: true
    description: "Kubernetes cluster zone"
  HELM_VERSION:
    required: false
    default: "v3.6.0"
    description: "Helm version to use"
outputs: {}
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ inputs.GCP_PROJECT_ID }}
        service_account_key: ${{ inputs.GCP_SA_KEY }}
        export_default_credentials: true

    - name: configure docker to use gcloud registry
      run: gcloud auth configure-docker ${{ inputs.GCP_DOCKER_REGISTRY }} # configure-docker command does expects specific registries
      shell: bash # default for whole file for composite actions ? blah

    - name: print docker/config.json
      run: cat ~/.docker/config.json
      shell: bash

    - name: build docker image
      run: docker build --tag ${{ inputs.DOCKER_IMAGE_TAG }} .
      shell: bash

    - name: push docker image
      run: docker push ${{ inputs.DOCKER_IMAGE_TAG }}
      shell: bash

    - name: configure kubectl to use the specified gcloud k8s cluster
      run: gcloud container clusters get-credentials ${{ inputs.GCP_K8S_CLUSTER_ID }} --zone ${{ inputs.GCP_K8S_CLUSTER_ZONE }}
      shell: bash

    - uses: azure/setup-helm@v1
      with:
        version: ${{ env.HELM_VERSION }}
