name: deploy
description: none
inputs:
  GCP_PROJECT_ID:
    required: true
  DOCKER_IMAGE_TAG:
    required: true
outputs: {}
runs:
  using: composite
  steps:
    - name: test
      run: echo "🎉 deploy ${{ inputs.GCP_PROJECT_ID }}"
      shell: bash
