apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
        - name: simple-container
          image: europe-west3-docker.pkg.dev/simple-326714/docker/simple:latest
          ports:
            - name: http
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: simple-service
spec:
  type: LoadBalancer
  selector:
    app: simple
  ports:
    - name: http
      protocol: TCP
      targetPort: 3000
      port: 80
