name: pull_request

on:
  push:
    branches:
      - develop

env:
  GCP_DOCKER_REGISTRY: europe-west3-docker.pkg.dev
  GCP_K8S_CLUSTER_ID: simple-cluster
  GCP_K8S_CLUSTER_ZONE: europe-west1-b
  DOCKER_IMAGE_TAG: europe-west3-docker.pkg.dev/simple-326714/docker/simple:${{ github.sha }}

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm run lint
      - run: npm run tsc
      - run: npm run test
      - uses: ./.github/actions/deploy
        name: deploy
        with:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GCP_DOCKER_REGISTRY: ${{ env.GCP_DOCKER_REGISTRY }}
          GCP_K8S_CLUSTER_ID: ${{ env.GCP_K8S_CLUSTER_ID }}
          GCP_K8S_CLUSTER_ZONE: ${{ env.GCP_K8S_CLUSTER_ZONE }}
          DOCKER_IMAGE_TAG: ${{ env.DOCKER_IMAGE_TAG }}
