name: deploy_dev

on: 
  workflow_dispatch:
    inputs:
      env:
        required: true
        description: 'Environment (development, production)'     
      version:
        required: true
        description:  'Version to deploy ( eg. v1.13; should be available in Artifact Registry )'

env:
  ENV: ${{ inputs.env }}
  APP_NAME: simple
  GCP_PROJECT_ID: simple-326714
  GCP_REGISTRY: europe-west3-docker.pkg.dev
  HELM_VERSION: v3.6.0
  HELM_RELEASE_NAME: simple-helm-release
  
  VERSION: ${{ inputs.version }}
  HELM_CHART_REF: ${{ env.GCP_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/docker/${{ env.APP_NAME }}:${{ env.VERSION }}
  HELM_CHART_REF: ${{ env.GCP_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/helm/${{ env.APP_NAME }}:${{ env.VERSION }}

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - uses: azure/setup-helm@v1
        with:
          version: ${{ env.HELM_VERSION }}
      
      - name: configure helm to use artifact registry
        run: gcloud auth print-access-token | helm registry login -u oauth2accesstoken --password-stdin ${{ env.GCP_REGISTRY }}

      - name: pull helm chart
        run: helm chart pull 
      - name: deploy
        run: helm upgrade \
        ${{ env.HELM_RELEASE_NAME }} ${{ env.HELM_CHART_REF }} \
        --values helm/values-${{ env.ENV }}.yaml \
        --install \
        --reset-values \
        --wait




