name: pull_request

on: [push]

env:
  NODE_VERSION: 14.17.0

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm install --global yarn

      - run: yarn lint

      - run: yarn tsc

      - run: yarn test

      - run: yarn build
