name: release

on:
  release:
    types: [published]
env:
  #            gc location for registry -docker.pkg.dev
  GC_REGISTRY: europe-west3-docker.pkg.dev
  #                        gc project / registry folder / project ( as in app ) name
  GC_REGISTRY_DOCKER_PATH: simple-326714/docker/simple
  VERSION: ${{ github.event.release.tag_name }}

  # for simplicity
  DOCKER_IMAGE_TAG: europe-west3-docker.pkg.dev/simple-326714/docker/simple:${{ github.event.release.tag_name }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build docker image
        run: docker build --tag ${{ env.DOCKER_IMAGE_TAG }}
      - name: push docker image
        run: docker push ${{ env.DOCKER_IMAGE_TAG }}
