name: release
author: is

on:
  release:
    types: [published]

runs:
  steps:
    - run: echo 'tag published event'
    # - uses: actions/checkout@v2
    # - name: create git tag

    # - name: build image
    # - name: push image to repo
